project:
  type: website

website:
  title: "Геоинформационные системы"
  navbar:
    left:
      - href: index.qmd
        text: Лекции
      - href: about.qmd
        text: О курсе
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

