---
title: "Геоинформационные системы. О курсе"
date: today
date-format: "D MMMM YYYY"
number-sections: false
author:
  - affiliation: Институт дизайна и урбанистики, Университет ИТМО 
    name: Балтыжакова Татьяна
---

## Преподаватель курса {.unnumbered}

Балтыжакова Татьяна Игоревна, кандидат технических наук, доцент Института дизайна и урбанистики.

::: callout-note
## Цитирование материалов

*Балтыжакова Т.И.* **Геоинформационные системы** : сайт. 2026. — URL: <https://baltti.github.io/bachelor-gis-course/>. DOI: [10.5281/zenodo.19050322](https://doi.org/10.5281/zenodo.19050322)
:::

# О чем эта дисциплина?

Курс знакомит студентов с теоретическими основами и программным обеспечением геоинформатики применительно к городским исследованиям.

В рамках курса изучаются основы картографии, принципы организации данных в ГИС, основыне методы пространственного анализа (оверлей, буферизация) и работа с открытыми источниками геоданных (OSM, государственные порталы).

Целью курса является освоение студентами-урбанистами современных ГИС-инструментов.

# Промежуточная аттестация по курсу

В конце курса вас ожидает **экзамен**.

Оценка за экзамен складывается из трех составляющих:

| №   | Составляющая экзамена      | Баллы |
|-----|----------------------------|-------|
| 1   | Домашняя работа            | 0-60  |
| 2   | Теоретическое тестирование | 0-20  |
| 3   | Практическое задание       | 0-20  |

::: callout-important
Выполнение домашней работы является обязательным.

Те, кто не ее не сдадут, не будут допущены к экзамену.
:::

Перечень вопросов и примерных заданий будет опубликован позднее.

::: callout-tip
## Обратная связь

Если вы заметили ошибку или опечатку, можете написать мне на почту tibaltyzhakova\@itmo.ru или оставить [issue](https://github.com/baltti/bachelor-gis-course/issues) в репозитории курса на GitHub.
:::
